// AUTO-GENERATED by scripts/generate-navigation.mjs
// Source: wiki/index.md → S3 portfolio-docs/manifest.json → here
// Do not edit manually — run `npm run wiki:fetch` to regenerate.

export const navigation = [
  {
    title: 'Overview',
    links: [
    {
      title: 'Home',
      href:  '/',
    },
    ],
  },
  {
    title: 'Projects',
    links: [
    {
      // CDK-managed self-hosted Kubernetes bootstrap pipeline on EC2 with Step Functions and SSM
      title: 'K8s Bootstrap Pipeline',
      href:  '/docs/k8s-bootstrap-pipeline',
    },
    ],
  },
  {
    title: 'Concepts',
    links: [
    {
      // kubeadm on EC2: what managed K8s provides that self-hosted does not, and how bootstrap scripts fill 
      title: 'Self Hosted Kubernetes',
      href:  '/docs/self-hosted-kubernetes',
    },
    {
      // local-first testing philosophy: unit tests (5s) → dry-run (30s) → SSM trigger (1min) → CI pipeline (
      title: 'Shift Left Validation',
      href:  '/docs/shift-left-validation',
    },
    ],
  },
  {
    title: 'Tools',
    links: [
    {
      // orchestration engine for bootstrap (SM-A) and config injection (SM-B) state machines
      title: 'Aws Step Functions',
      href:  '/docs/aws-step-functions',
    },
    {
      // remote execution layer: Run Command, Session Manager, Parameter Store — replaces SSH entirely
      title: 'Aws Ssm',
      href:  '/docs/aws-ssm',
    },
    {
      // Calico CNI via Tigera operator: pod networking and NetworkPolicy enforcement
      title: 'Calico',
      href:  '/docs/calico',
    },
    {
      // AWS Cloud Controller Manager: removes cloud provider taint to unblock pod scheduling
      title: 'Aws Ccm',
      href:  '/docs/aws-ccm',
    },
    {
      // GitOps controller: declarative workload management from Git after bootstrap
      title: 'Argocd',
      href:  '/docs/argocd',
    },
    {
      // CI/CD with OIDC credential federation, custom Docker CI image, path-scoped monorepo triggers
      title: 'Github Actions',
      href:  '/docs/github-actions',
    },
    {
      // task runner: developer CLI wrapping all deploy, bootstrap, and CDK workflows
      title: 'Just',
      href:  '/docs/just',
    },
    ],
  },
  {
    title: 'Patterns',
    links: [
    {
      // SM-A SUCCEED → EventBridge → SM-B auto-fires: self-healing config injection
      title: 'Event Driven Orchestration',
      href:  '/docs/event-driven-orchestration',
    },
    {
      // custom Step Functions poll loop for SSM Run Command completion (no native waiter exists)
      title: 'Poll Loop Pattern',
      href:  '/docs/poll-loop-pattern',
    },
    ],
  },
  {
    title: 'Troubleshooting',
    links: [
    {
      // EACCES on /data/app-deploy/ from ssm-shell: root cause (root:root 755) and two-layer fix (group-writ
      title: 'Ssm Permission Denied',
      href:  '/docs/ssm-permission-denied',
    },
    ],
  },
  {
    title: 'Commands',
    links: [
    {
      // complete command reference: just recipes, AWS CLI, SSM debugging, CDK operations
      title: 'K8s Bootstrap Commands',
      href:  '/docs/k8s-bootstrap-commands',
    },
    ],
  },
  {
    title: 'Comparisons',
    links: [
    {
      // LLM Wiki vs Bedrock article pipeline: where each excels, hybrid architecture proposal, 3-phase migra
      title: 'Llm Wiki Vs Bedrock Pipeline',
      href:  '/docs/llm-wiki-vs-bedrock-pipeline',
    },
    ],
  },
]
